name: big-bear-cloudflared-web
services:
  big-bear-cloudflared-web:
    cpu_shares: 90
    command: []
    container_name: big-bear-cloudflared-web
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - BASIC_AUTH_PASS=$[password]
      - BASIC_AUTH_USER=$[username]
      - EDGE_IP_VERSION=auto
      - METRICS_ENABLE=false
      - METRICS_PORT=60123
      - PROTOCOL=auto
      - WEBUI_PORT=14335
    hostname: big-bear-cloudflared-web
    image: wisdomsky/cloudflared-web:2026.3.0
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/cloudflare.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-cloudflared-web/config
        target: /config
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    network_mode: host
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Cloudflared-web is a docker image that packages both cloudflared cli and
      a simple Web UI to easily start or stop remotely-managed Cloudflare
      tunnel.
  developer: wisdomsky
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/cloudflare.png
  index: /
  is_uncontrolled: false
  main: big-bear-cloudflared-web
  port_map: "14335"
  scheme: http
  store_app_id: big-bear-cloudflared-web
  tagline:
    en_us: Cloudflared Web
  thumbnail: ""
  tips:
    before_install:
      en_us: >
        Read this before installing:
        https://community.bigbeartechworld.com/t/added-cloudflared-web-to-bigbearcasaos/2275?u=dragonfire1119
  title:
    custom: ""
    en_us: Cloudflared Web
