name: big-bear-it-tools
services:
  app:
    cpu_shares: 90
    container_name: big-bear-it-tools
    deploy:
      resources:
        limits:
          memory: 7367M
    hostname: big-bear-it-tools
    image: corentinth/it-tools:2023.11.2-7d94e11
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/it-tools.png
    ports:
      - mode: ingress
        target: 80
        published: "8082"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    command: []
    environment: []
    networks:
      - default
    privileged: false
networks:
  default:
    name: big-bear-it-tools_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Collection of handy online tools for developers, with great UX as a web
      app.
  developer: corentinth
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/it-tools.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: "8082"
  scheme: http
  store_app_id: big-bear-it-tools
  tagline:
    en_us: IT Tools
  thumbnail: ""
  title:
    custom: ""
    en_us: IT Tools
